rate: 50
device_id: 16

iq_controller:
  #   [       kp,       ki,       kd,      ff0,     ff1,      ff2,  timeout]
  m1: [ 0.000622,      0.0,      0.0,      0.0, 0.00457,      0.0,      5.0]
  m2: [ 0.000622,      0.0,      0.0,      0.0, 0.00457,      0.0,      5.0]
  m3: [ 0.000622,      0.0,      0.0,      0.0, 0.00457,      0.0,      5.0]
  m4: [ 0.000622,      0.0,      0.0,      0.0, 0.00457,      0.0,      5.0]